### ISSUE TITLE
Using MAS code to create a side project for "suggests" fields

### ISSUE THREAD

**Issue by marcbourlon** [douglascayers-org/sfdx-mass-action-scheduler#117]
## Is your feature request related to a problem? Please describe.

When people create LC or LWC "suggests" form components (type some characters and see a list of filtered results show, and get filtered more as you type), they have to do an Apex controller.

## Describe the solution you'd like.

MAS genius way of choosing an input (List, SOQL, etc.) in a declarative fashion can probably be used with small changes to remove the need for a custom Apex controller. Here's how I would use it, from a LC or LWC:
1. in the .cmp, declare the controller as DeclarativeSuggestController (assuming we name the class this way)
2. in the client-side controller, instead of calling our custom made controller, we instead set parameters like:
{
sourceType: 'Listview',
listViewName: 'XXXXXXXXXX',
filterByCharacters: 'arc',
}
or
{
sourceType: 'Flows',
flowsName: 'Select_Platinum_Partners',
filterByCharacters: 'Best',
}

etc.

## Describe alternatives you've considered.

Doing it myself, but there's a chance it does not take much time to Douglas to do it.

**Comment by douglascayers** [comment]
Hi @marcbourlon, 

Thanks for the feedback and I'm honored you hold me in such high esteem.

I believe the feature you're looking for is https://github.com/pozil/sfdc-ui-lookup, developed by another amazing developer evangelist at Salesforce, [Philippe Ozil](https://twitter.com/@PhilippeOzil).

Thanks

**Comment by marcbourlon** [comment]
Hi Douglas. I don't think this component does it. The backend is pure Apex.
