### ISSUE TITLE
Anonymous Apex 

### ISSUE THREAD

**Issue by gurditta** [douglascayers-org/sfdx-mass-action-scheduler#118]
Hi Doug,

First of all thanks for this package it's super useful and can save hours.

I've trying this first and have a simple requirement to change email address of email fields on Contacts to some invalid emails. I'm trying this below code block but it's not working. I know I can achieve via Process Builder or quick action but I wanna do through Apex as I'll deploy this to prod and every sandbox will have it. below is the code I wrote:

```
void execute(List<Map<String, Object>> sourceRecordsBatch) { 
    List<sObject> toBeUpdated = new List<sObject>();
    for(Map<String, Object> temp : sourceRecordsBatch) {
        Map<String, Schema.SObjectType> gd = Schema.getGlobalDescribe();
        Schema.SobjectType oType = gd.get(temp.get('attributes.type'));
        sobject object_instance = oType.newSObject();
        object_instance.put('Email', temp.get('Email') + '.invalid');
        object_instance.put('Id', temp.get('Id'));
        toBeUpdated.add(object_instance);
    }
    system.debug('########## => ' + toBeUpdated);
    update toBeUpdated;
}
```

I'm getting this error:

> First error: Anonymous Apex Error:
> compileProblem: Method does not exist or incorrect signature: void get(Object) from the type Map<String,Schema.SObjectType>

**Comment by douglascayers** [comment]
Closing issue since there’s been no follow up comments. If you still need assistance please reply and I’ll reopen the issue. Thanks for your interest in Mass Action Scheduler!
