### ISSUE TITLE
Scheduled Job not running in Sandbox

### ISSUE THREAD

**Issue by kmoser13** [douglascayers-org/sfdx-mass-action-scheduler#124]
This is more of a question than an issue. For the past several months, we have noticed that the Scheduled Mass Action Configurations are not running in the sandbox (we believe it was after the sandbox was refreshed). 

We recently upgraded to the latest release in the sandbox to see if that would correct the issue, but it doesn't appear to have had an impact.

Is there something that we are missing or is there a way to troubleshoot why this would be happening?  Any insight would be greatly appreciated. 

Thank you!

**Comment by cchrisv** [comment]
You'll need to manually run through the setup steps to configure a sandbox after a refresh. The urls are likely still pointing to production.

**Comment by kmoser13** [comment]
I will give that a try - thanks for the recommendation @cchrisv!

**Comment by douglascayers** [comment]
Thanks @cchrisv, that's definitely something I would recommend after a sandbox is refreshed is make sure any URL configurations match the sandbox org. Especially if you're using Named Credentials then you'll need to update those configurations with the updated sandbox domain.
