### ISSUE TITLE
Running screen Flows?

### ISSUE THREAD

**Issue by marcbourlon** [douglascayers-org/sfdx-mass-action-scheduler#128]
## Is your feature request related to a problem? Please describe.

Hi Doug! I use Flow Actions (aura component) to do some string manipulation too tricky to do in Flows. However, I had to convert my Flows to Screen Flows to do that, and because of that, I cannot select them in the MAS anymore. Is it a MAS limitation, of a SF platform limitation?

## Describe the solution you'd like.

Being able to select Screen Flows, with a warning that it may not work if there are screens. I kind of guess Aura components do need screens to run?

## Describe alternatives you've considered.

I'll probably have to fallback to Apex action :-(

## Additional context.

Love MAS always!

**Comment by douglascayers** [comment]
Hi @marcbourlon,

Glad you're enjoying Mass Action Scheduler =)

Unfortunately, the Actions REST API only supports autolaunched flow types -- so no screens are allowed. This is a system limitation.

If you switch from using a Lightning Component in your Flow to instead using [Invocable Apex](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_classes_annotation_InvocableMethod.htm) then you may be able to save your flow against as autolaunched and use it with MAS.

Thanks for the feedback, as always
