### ISSUE TITLE
Spring 20 Org Error - Apex script unhandled exception by user/organization

### ISSUE THREAD

**Issue by cchrisv** [douglascayers-org/sfdx-mass-action-scheduler#132]
## Summary
Since my full copy sandbox was upgraded to Spring 20 I've started receiving the following error:

Failed to process batch for class 'dca_mass_action.MA_ReportSourceBatchable' for job id '707q000002IlgSE'

caused by: dca_mass_action.MA_Exceptions.InvokeActionException: Invoke Action Error: System.HttpResponse[Status=Temporary Redirect, StatusCode=307]
<Errors>
<Error>
<errorCode>INVALID_SESSION_ID</errorCode>
<message>Session expired or invalid</message>
</Error>
</Errors>

## Version of Mass Action Scheduler

 2.301

## Steps To Reproduce

1. Run job in a Spring 20 org

## Expected Behavior
1. Run without error

## Actual Result
1. Job fails

## Source Type

- [ x] Reports
- [ ] List Views
- [ ] SOQL Queries

## Action Type

- [ ] Process Builder & Flows
- [ ] Workflow Rules
- [ ] Email Alerts
- [ ] Quick Actions
- [ ] Apex

**Comment by douglascayers** [comment]
Hi @cchrisv,

If you're using Named Credentials, you may need to re-create them.

Additionally, review any Critical Updates and the Release Notes that the Spring '20 release introduces in case that release has an impact on your configured actions.

If you can provide steps to recreate your configuration then I can try things out on my end to see if I can reproduce the issue.

Also, you might try upgrading to the latest 2.4 release I just put out: https://github.com/douglascayers-org/sfdx-mass-action-scheduler/wiki/Release-Notes

Thanks
