### ISSUE TITLE
Spring 20 Error - First error: [The sort column name must be from a selected column.]	

### ISSUE THREAD

**Issue by cchrisv** [douglascayers-org/sfdx-mass-action-scheduler#134]
## Summary
Since sandbox was upgraded to Spring 20 I am seeing the following errors:
First error: [The sort column name must be from a selected column.]	

## Steps To Reproduce
Update to Winter org to Spring 2020

## Expected Behavior
No error

## Actual Result
Job fails

## Source Type

- [ x] Reports
- [ ] List Views
- [ ] SOQL Queries

## Action Type

- [ x] Process Builder & Flows
- [ ] Workflow Rules
- [ ] Email Alerts
- [ ] Quick Actions
- [ ] Apex

## Does your configuration use Named Credentials?
Yes

**Comment by douglascayers** [comment]
Hi @cchrisv, I also followed up on your [question on the community](https://success.salesforce.com/0D53A00004h7ncE). I'll need to test in a Spring '20 org, I haven't done that yet. But my first guess regardless is confirm the field from the report you choose on the Mass Action Configuration page as the unique sort field still exists on the report **and** that the running user (or context user of the Named Credential if using one) still has access to the field.
