### ISSUE TITLE
Scheduling MAS Configuration on Refreshed (or Cloned) Sandbox

### ISSUE THREAD

**Issue by JeroenSfdc** [douglascayers-org/sfdx-mass-action-scheduler#140]
## Summary
On refreshed sandbox, scheduling an existing MAS configuration requires making changes to the schedule.

## Version of Mass Action Scheduler
`2.302`

## Steps To Reproduce
Refresh a sandbox from production or clone a sandbox which has an existing MAS configuration.
Click through the steps of the MAS configuration and save it
Verify the Scheduled Apex jobs and see that the MAS configuration has not been scheduled. 

## Expected Behavior
MAS configuration should be scheduled w/o making changes to it. 

## Actual Result
No scheduled job.

## Source Type
- [X] Reports
- [X] List Views
- [X] SOQL Queries

## Action Type
- [X] Process Builder & Flows
- [X] Workflow Rules
- [X] Email Alerts
- [X] Quick Actions
- [X] Apex

## Does your configuration use Named Credentials?
- [X] Yes
- [X] No

**Comment by cchrisv** [comment]
In my sandboxes I only need to de-active the MAS COnfig and reactivate for it to work. This is because the batchjobs need to be rescheduled. You can do this in mass from a list view. It takes a few minutes.

**Comment by JeroenSfdc** [comment]
Thanks for that suggestion @cchrisv.
