### ISSUE TITLE
Error: System.HttpResponse[Status=Bad Request, StatusCode=400]

### ISSUE THREAD

**Issue by SalesforceBobLightning** [douglascayers-org/sfdx-mass-action-scheduler#69]
Hi Doug,

Congrats on v2 - excellent work :)

I am getting the below error appearing in the log:

> Error: System.HttpResponse[Status=Bad Request, StatusCode=400]
> [{"actionName":"Invoice__c.Set_Status_to_Paid","errors":[],"isSuccess":true,"outputValues":null},{"actionName":"Invoice__c.Set_Status_to_Paid","errors":[],"isSuccess":true,"outputValues":null}

As you can see, the error actually returns `isSuccess:true` 

And the records are being updatd.

But it's still telling me `Status=Bad Request, StatusCode=400`

Thought you'd want to know.

Config:

Data Source: ListView
Using: Quick Action: Update a record
Triggered: Manually

**Comment by SalesforceBobLightning** [comment]
I fixed this by reducing the batch to 100

**Comment by douglascayers** [comment]
Good detective work, @SalesforceBobLightning!

I was confused why you'd get a failure but the log was saying some records were successful. After you mentioned reducing the batch size that's when it dawned on me that of the 200, some **did** succeed but some did not, and the ones that failed caused the error HTTP response.
