### ISSUE TITLE
Old manual instructions gone

### ISSUE THREAD

**Issue by cchrisv** [douglascayers-org/sfdx-mass-action-scheduler#77]
I should have saved the manual instructions on how setting up a Named Credential. I'm still using 1.6 and had to refresh a sandbox. Where can I find the old instructions?

**Comment by douglascayers** [comment]
Hi @cchrisv, thanks for your interest in Mass Action Scheduler!

You can find documentation on the [Wiki](https://github.com/douglascayers-org/sfdx-mass-action-scheduler/wiki) tab here on GitHub.

For Named Credentials, see [this page](https://github.com/douglascayers-org/sfdx-mass-action-scheduler/wiki/Specify-the-Running-User-via-Named-Credentials).

I encourage you to upgrade to the [latest version](https://github.com/douglascayers-org/sfdx-mass-action-scheduler#packaged-release-history). Let me know if you have any issues.

Thanks
