### ISSUE TITLE
Update documentation with option to use Domain whitelisting instead of disabling Clickjack protection?

### ISSUE THREAD

**Issue by JeroenSfdc** [douglascayers-org/sfdx-mass-action-scheduler#85]
![image](https://user-images.githubusercontent.com/27854769/57284557-b3d34300-70b1-11e9-9f18-d6bc0ddf2ed2.png)

## Is your feature request related to a problem? Please describe.
Seems to work fine with domain whitelisting. Not better than asking to disable Clickjack protection?

## Describe the solution you'd like.
Whitelisted Domains
```
https://*.lightning.force.com
https://*.visualforce.com
```

**Comment by douglascayers** [comment]
Thanks, @JeroenSfdc! I'll try it out and update the docs. This seems far less scary than telling people to disable clickjack protection

**Comment by douglascayers** [comment]
Prior to Spring '19, the only option I was aware of was disabling clickjack protection on visualforce pages.

Introduced in Spring '19, we now have the option to [Allow External iframes of Visualforce Pages with Clickjack Protection](https://releasenotes.docs.salesforce.com/en-us/spring19/release-notes/rn_vf_external_iframe.htm).

**Comment by douglascayers** [comment]
@JeroenSfdc I've updated the documentation at https://github.com/douglascayers-org/sfdx-mass-action-scheduler/wiki/Pre-Requisites-Instructions#3-allow-iframing-of-visualforce-pages-with-clickjack-protection

Please have a look and let me know what you think.

I confirmed in one of my test orgs that whitelisting the domains still allowed the app to work when clickjack protection was enabled.

![Uploading image.png…]()


Thanks

**Comment by JeroenSfdc** [comment]
Very nicely documented now @douglascayers! Top!
