### ISSUE TITLE
No Source, Just Flow

### ISSUE THREAD

**Issue by Tiger5K** [douglascayers-org/sfdx-mass-action-scheduler#91]
I have several flows that I would like to schedule to run daily.  Some are subflows of others.  They retrieve and process their own records from Accounts and several other custom objects. (using Get Records/Loop/Assignment/Create Records...etc.)

I don't need to provide 'source' records externally.  I just need to schedule their launch.
Can I do this with Mass Action?  If so, how?  FYI, I'm new to Mass Actions... Thanks.

**Comment by douglascayers** [comment]
Hi @Tiger5K, thanks for using Mass Action Scheduler. You can achieve this with the SOQL source type and use a query that returns one record, like `SELECT Id FROM Organization LIMIT 1`. On the Field Mappings step, you wouldn't assign any values from the query to your flow, so you could skip on to the scheduling piece.
