### ISSUE TITLE
MAS passing less rows to apex than validate soql says it will

### ISSUE THREAD

**Issue by GeorgeP01** [douglascayers-org/sfdx-mass-action-scheduler#92]
## Summary

I have this query in MAS:
select Id, field, accountId, createdDate, newValue, oldValue from AccountHistory
where createdDate = TODAY
When i validate it returns 4 rows, which is what i expect from my sandbox given the data in it.
Ie, 4 edits have occurred to an account.
Rows returned are 3 rows with new value populated and 1 row with newvalue blanked out (or set to null)
However when I run the MAS and pass result to an invocable apex method, then only 3 rows are being passed in.   The row that has the newValue set to null is not being passed to my apex invocable method and it needs to be.

## Version of Mass Action Scheduler

Version 2.2

## Steps To Reproduce

Edit some account records and set some fields to non-blank and then to blank values.
Run history report to check rows are correctly reported.
Validate SOQL in MAS to check same number of rows are reported.
Run MAS with above soql and pass to an invocable method
Display results received by invocable method.
In my case the rows that have newvlaue set to blank are being ommitted.

1. List steps that cause the issue
see above

2. Screen shots are also helpful

## Expected Behavior

Rows passed to invocable method should = rows reported by validate SOQL

## Actual Result

History rows that have newvlaue set to blank are being ommitted.

## Source Type

- [ ] Reports
- [ ] List Views
- [X] SOQL Queries

## Action Type

- [ ] Process Builder & Flows
- [ ] Workflow Rules
- [ ] Email Alerts
- [ ] Quick Actions
- [X] Apex

## Does your configuration use Named Credentials?
No, it does not

**Comment by douglascayers** [comment]
Thanks for the detailed report @GeorgeP01.

To help me troubleshoot, could you share the definitions of your @InvocableMethod and @InvocableVariable fields of the class your calling?

I'll try to reproduce on my end, too.

**Comment by douglascayers** [comment]
Do you notice the same behavior when using a **Report** as the data source instead of **SOQL**?

**Comment by GeorgeP01** [comment]
Hi Douglas
the invocable methods is this:

@InvocableMethod(label='Link and Unlink Contract Accounts'   description='This is used to manage the linking or unlinking of contract accounts that have moved out or in')
public static List<String> LinkUnlinkContractAccounts(List<accountHistoryRecords> sourceRecordsBatch) {

The invocable variables are as follows:
	public class accountHistoryRecords {
		@InvocableVariable(Label = 'History Row Id' required=true)
		public String Id;

		@InvocableVariable(Label = 'History Field' required=true)
		public String field;

		@InvocableVariable(Label = 'Account Id' required=true)
		public String accountId;

		@InvocableVariable(Label = 'New Value' required=true)
		public String newValue;
	}

The MAS screen looks like this
![image](https://user-images.githubusercontent.com/46985138/59016819-bbcf0000-8874-11e9-80f4-e6957ea3f552.png)

The filed mapping is this:
![image](https://user-images.githubusercontent.com/46985138/59016856-d2755700-8874-11e9-9d2b-db40a51bd871.png)

I just tried again with 2 history records, 1 where the new value field has a value and one where it is blank, ie value removed.    Only the non-blank record is passed to my apex class from the MAS soql query.

I will try with a report as well for a data source.

kind regards
George

**Comment by GeorgeP01** [comment]
Here is the query
![image](https://user-images.githubusercontent.com/46985138/59017230-9ee6fc80-8875-11e9-8b9a-c3dc41f5bb95.png)

**Comment by douglascayers** [comment]
Thanks @GeorgeP01, this is very helpful. 

From what I can tell, you’re doing everything correctly. I’ll dig into it.

**Comment by Xixiao007** [comment]
Here is what I found in the debug log so far.

1. The correct number of records is passed to invocableMethod `TestRunInvocable`
```
CALLOUT_REQUEST [996]|System.HttpRequest[Endpoint=https://force-ability-9922-dev-ed.cs85.my.salesforce.com/services/data/v45.0/actions/custom/apex/TestRunInvocable, Method=POST]
```
2. API returns 200 OK
```
CALLOUT_RESPONSE [996]|System.HttpResponse[Status=OK, StatusCode=200]
```
3. In the subsequent user debug log, it seems the `newValue` field is required/mandatory for whatever reason.
```
USER_DEBUG [999]|DEBUG|[{"actionName":"TestRunInvocable","errors":[{"statusCode":"REQUIRED_FIELD_MISSING","message":"Missing required input parameter: newValue","fields":[]}],"isSuccess":false,"outputValues":null},{"actionName":"TestRunInvocable","errors":[{"statusCode":"REQUIRED_FIELD_MISSING","message":"Missing required input parameter: newValue",&q
```

**Comment by douglascayers** [comment]
Thanks @xixiao007 for investigating and the follow up. I hadn’t had time to dig in yet. 

I agree with your assessment. The invocable variable for `newValue` should not be required as a field could have had its value set to null/blank. The required attribute means that the value passed to it must not be null/blank, but that’s actually a valid value for field history tracking. 

@GeorgeP01, please try this change and let us know how it goes. I’m pretty sure this is the fix. 

Thanks
