### ISSUE TITLE
Action not saving if setup is run multiple times 

### ISSUE THREAD

**Issue by cwland** [douglascayers-org/sfdx-mass-action-scheduler#94]
Hi All, 

I’ve had a couple of users receive an error of ‘SetParams’ of null when trying to run a Mass Action.  Upon investigation, I found that the Action was blank.   Initially, I thought they had changed it but turns out they are running through the setup each time to click ‘Validate Query’ to see population before sending an email.   Turn out if you run through the setup multiple times in a row, the Action will not be saved after the first loop.   

Video of the issue: https://www.screencast.com/t/fE7uvY9J

Thanks,

-Cory

Version 2.2
1) Open a mass action with an email alert. 
2) Run through the setup and select Save
3) Select Next and run through the process a second time.   The Action will be missing. 

## Expected Behavior
I expect the Action to remain regardless of how many time the wizard is run

## Actual Result
Currently, the Action will blank out if the setup is run multiple times in a row.

## Source Type

- [ ] Reports
- [ ] List Views
- [X] SOQL Queries

## Action Type

- [ ] Process Builder & Flows
- [ ] Workflow Rules
- [X] Email Alerts
- [ ] Quick Actions
- [ ] Apex

## Does your configuration use Named Credentials?
Yes

**Comment by douglascayers** [comment]
Apologies for the bug, @cwland. Thank you so much for the video and digging in to how to reproduce this.

**Comment by jensanald** [comment]
Hi there, I am running into the same issue. The only difference is I am using source type Report and Action Type Process Builder and Flows.  The action intermittently disappears.  This was working fine during the past month and the issue started as of yesterday.

**Comment by douglascayers** [comment]
In my initial debugging... this seems very baffling. My code queries for the configuration record and **sometimes** I receive the target action field value (good) but **sometimes** I don't, it comes back null (bad).

All other field values seem unaffected. And yet, all the fields are queried and processed the same.

Still investigating....

**Comment by jensanald** [comment]
Right! It is inconsistent and some of my configurations are unaffected and don't lose its action. It seems like the ones that are scheduled don't lose the action as frequent as the ones with no schedule. The on demand tend to lose their action more frequently. I will keep you posted.  Thanks for looking into this!

**Comment by douglascayers** [comment]
I believe I've found the culprit. There was a race condition (code running in parallel) that was conflicting with rendering the correct Action Type.

This fix will be included in the upcoming release v2.3, tentatively scheduled for later this week.

Thank you for your patience and for bringing this issue to my attention.

**Comment by jensanald** [comment]
Hi there, 
Just checking on the status of v2.3 release. Are you planning to release any time soon? Anxiously awaiting for the new version!  Thank you!!

**Comment by JeroenSfdc** [comment]
> I believe I've found the culprit. There was a race condition (code running in parallel) that was conflicting with rendering the correct Action Type.
> 
> This fix will be included in the upcoming release v2.3, tentatively scheduled for later this week.
> 
> Thank you for your patience and for bringing this issue to my attention.

I belief as a cause of this, I saw in my environment jobs running at the same scheduled time for the same configuration. This happened after I 're-saved' the configuration I used SOQL as source, and Flow as target. I got Flow exceptions that the target record from the SOQL source could not be found in the initial query step in the flow.

**Comment by jensanald** [comment]
Thank you!!!

**Comment by douglascayers** [comment]
You're very welcome, @jensanald.

Release 2.3 is now available per #99, please see the [release notes](https://github.com/douglascayers-org/sfdx-mass-action-scheduler/wiki/Release-Notes-v2.3) for full details. Thank you!
