### ISSUE TITLE
Scheduled MAS not running at planned time

### ISSUE THREAD

**Issue by MikeVenman** [douglascayers-org/sfdx-mass-action-scheduler#95]
I have a scheduled action that I've had running for the past several months which stopped running at the planned time.  I haven't changed anything and am curious as to what could have caused it to stop.

The Source is a report, but it doesn't have more than 1000 record to update at any one time.

I'm not getting any flow errors nightly and it's saying that it hasn't run since 5/24.

Schedule Frequency is "Scheduled" - Time is 1:00 AM - I've selected every day of the week - I haven't selected any day of the month - I've selected every month.

The Mass Action Scheduler is "Active".

Can you think of anything I'm missing?  Thank you!

## Steps To Reproduce

1. List steps that cause the issue
2. Screen shots are also helpful

## Source Type

- [x] Reports
- [ ] List Views
- [ ] SOQL Queries

## Action Type

- [x] Process Builder & Flows
- [ ] Workflow Rules
- [ ] Email Alerts
- [ ] Quick Actions
- [ ] Apex

**Comment by MikeVenman** [comment]
I also ran the flow just now, ran perfectly without any errors, seems to be a scheduling thing.

**Comment by douglascayers** [comment]
Hi @mikevenman,

Thanks for your interest in Mass Action Scheduler. 

Sounds like the issue may be on the Salesforce side if it suddenly stopped running. Please try inactivating the configuration record then activate it again. That will reschedule the job in case something is wrong with the current scheduled job.

**Comment by MikeVenman** [comment]
Reactivating it seems to have done the job.  It ran successfully each day over the weekend.  

Anything that could have caused it to just stop working?  Could have been some other job getting in the way?  What about restarting it would make it work in the long term?  

Thanks for the help.  Love Love this tool.

**Comment by douglascayers** [comment]
Thanks for the update @MikeVenman. I'm not sure what could have caused the issue for the job to suddenly not run anymore. Maybe site maintenance of the org if it was recently upgraded to the next major release? Let me know if it happens again.

And thank you for the kind feedback, I'm glad you're enjoying the tool!
