### ISSUE TITLE
Apex Schedulable

### ISSUE THREAD

**Issue by tonygwardzen** [douglascayers-org/sfdx-mass-action-scheduler#97]
Does Mass Action Scheduler support the Apex Schedulable interface?

i.e. https://developer.salesforce.com/docs/atlas.en-us.220.0.apexcode.meta/apexcode/apex_scheduler.htm

**Comment by douglascayers** [comment]
Hi @tonygwardzen,

Yes, for configurations that are [scheduled](https://github.com/douglascayers-org/sfdx-mass-action-scheduler/wiki/Scheduling) then an instance of [MA_MassActionSchedulable.cls](https://github.com/douglascayers-org/sfdx-mass-action-scheduler/blob/2.2/force-app/main/default/classes/MA_MassActionSchedulable.cls) is scheduled.

A trigger on the `Mass_Action_Configuration__c` object schedules, unschedules, and reschedules jobs as the schedule options change or the record is activated/inactivated. See [here](https://github.com/douglascayers-org/sfdx-mass-action-scheduler/blob/2.2/force-app/main/default/classes/MA_MassActionConfigTriggerHandler.cls#L125) for those methods.
