### ISSUE TITLE
Last completed run tracking

### ISSUE THREAD

**Issue by Eshita91** [douglascayers-org/sfdx-mass-action-scheduler#98]
Hi Doug, 

First of all, thank you for an amazing tool. 

I just finished installing and setting it up on our production environment after testing on our lower environment. Everything went smoothly, hoping it stays the same. 

One thing I am trying to figure out is whether or not we can track the changes in the logs ? 
For example: I've created an invocable process builder to update records. The process will run everyday at the same time. I understand we receive error log details but what about successes ? 

Not sure if that's already an available functionality. I was hoping to see everyday how many records were updated, which ones, etc.. 

Thanks Again! 
Eshita

**Comment by douglascayers** [comment]
Great suggestion, @Eshita91, thank you. I'll see what I can do in an upcoming release

**Comment by douglascayers** [comment]
@Eshita91, apparently I have a similar enhancement request in the backlog, https://github.com/douglascayers-org/sfdx-mass-action-scheduler/issues/6. I'm going to close this issue and track the progress on the original. Please watch #6 for updates. Thanks!

**Comment by douglascayers** [comment]
Release 2.3 is now available per #99, please see the [release notes](https://github.com/douglascayers-org/sfdx-mass-action-scheduler/wiki/Release-Notes-v2.3) for full details. Thank you!
